# Default values for keycloak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  name: cfserver
  namespace: cm-dev
  profile: dev

replicaCount: 2

ingress:
  hosts:
    - cfserver.ndev.kyobobook.co.kr
  targetPort: http2

service:
  type: ClusterIP
  port: 80
  protocol: HTTP
  targetPort: 8080
  name: http


serviceMash:
  enabled: true
  istio: "true"
  jaeger: "true"


image:
  repository: image-registry.openshift-image-registry.svc:5000/cloud-dev/cfserver:0.0.1
  version: 0.0.1
  pullPolicy: IfNotPresent
  containerPort: 8080
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

serviceAccount:
  create: true # Specifies whether a service account should be created
  automount: true # Automatically mount a ServiceAccount's API credentials?
  annotations: {} # Annotations to add to the service account

autoscaling:
  memory:
    enabled: false
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
behavior:
  enabled: true
  podValue: 6
  percentValue: 10
  periodSeconds: 120
  stabilizationWindowSeconds: 180


# pv가 있으면 설정하자
volumeMounts: []