apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.app.name }} # cfserver
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: {{ .Values.service.port }}
        name: {{ .Values.service.name }}
        protocol: {{ .Values.service.protocol }}
      hosts: {{ .Values.ingress.host }}