apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: "{{ .Values.app.name }}-gw" # cfserver
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: {{ .Values.service.port }}  # 8080
        name: {{ .Values.service.name }}    # http
        protocol: {{ .Values.service.protocol }} # HTTP
      hosts: 
        {{- range .Values.ingress.hosts }} # dns 여러개
        - {{ . | quote }}
        {{- end }}