{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.name }} # cfserver
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ .Values.app.name }} # cfserver
  minReplicas: {{ .Values.autoscaling.minReplicas }} 
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}



# apiVersion: autoscaling/v1
# spec:
#   behavior:
#     scaleDown: 
#       policies: 
#       - type: Pods
#         value: 4
#         periodSeconds: 60
#       - type: Percent
#         value: 10
#         periodSeconds: 60
#       selectPolicy: Min
#       stabilizationWindowSeconds: 300
#     scaleUp: 9
#       policies:
#       - type: Pods
#         value: 5
#         periodSeconds: 70
#       - type: Percent
#         value: 12
#         periodSeconds: 80
#       selectPolicy: Max
#       stabilizationWindowSeconds: 0


  # metrics:
  #   {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
  #   - type: Resource
  #     resource:
  #       name: cpu
  #       target:
  #         type: Utilization
  #         averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  #   {{- end }}
  #   {{- if .Values.autoscaling.memory.enabled }}
  #   - type: Resource
  #     resource:
  #       name: memory
  #       target:
  #         type: Utilization
  #         averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  #   {{- end }}
  # {{- if .Values.behavior.enabled }}
  # behavior:
  #   scaleUp:
  #     stabilizationWindowSeconds: {{ .Values.behavior.stabilizationWindowSeconds }}
  #     policies:
  #       - type: Pods
  #         value: {{ .Values.behavior.podValue }}
  #         periodSeconds: {{ .Values.behavior.periodSeconds }}
  #       - type: Percent
  #         value: {{ .Values.behavior.percentValue }}
  #         periodSeconds: {{ .Values.behavior.periodSeconds }}
  #     selectPolicy: Max
  # {{- end }}
{{- end }}
