kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.app.name }}
  namespace: istio-system
  labels:
    app: {{ .Values.app.name }}
    maistra.io/gateway-name: "{{ .Values.app.name }}-gw"
    maistra.io/gateway-namespace: {{ .Values.app.namespace }}
    maistra.io/generated-by: ior
  annotations:
    maistra.io/original-host: {{ .Values.ingress.host }}
    haproxy.router.openshift.io/timeout: 24h
spec:
  host: {{ .Values.ingress.host }}
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  port:
    targetPort: {{ .Values.ingress.targetPort }}
  wildcardPolicy: None
# ---
# kind: Route
# apiVersion: route.openshift.io/v1
# metadata:
#   name: cfserver
#   namespace: istio-system
#   labels:
#     maistra.io/gateway-name: cfserver
#     maistra.io/gateway-namespace: cm-dev
#     maistra.io/generated-by: ior
#   annotations:
#     maistra.io/original-host: 
#     haproxy.router.openshift.io/timeout: 24h
# spec:
#   host: cfserver.ndev.kyobobook.co.kr
#   to:
#     kind: Service
#     name: istio-ingressgateway
#     weight: 100
#   port:
#     targetPort: cfserver.ndev.kyobobook.co.kr
#   wildcardPolicy: None
