{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name }} # cfserver

automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}