apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cfserver
spec:
  hosts: []
  http:
    - name: Canary
      match:
        - headers:
            rollout-version:
              exact: "Canary"
      route:
        - destination:
            host: {{ .Values.app.name }} # cfserver
            subset: Canary
    - name: Random
      route:
        - destination:
            host: {{ .Values.app.name }} # cfserver : service name
