apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}
spec:
  hosts:
  - "*"                          # gatewayname
  gateways:
  - {{ .Values.app.name }}       # gatewayname
  http:
    - name: Canary                                
      match:
        - headers:
            rollout-version:     # header name
              exact: "Canary"    # header value
            kb_canary:
              exact: kyobobook
      route:
        - destination:
            host: {{ .Values.app.name }} # cfserver
            subset: Canary       # 버전 특정 정책들 정의하고 service 레벨의 특정 설정을 overriding 합니다.
    - name: Random
      route:
        - destination:
            host: {{ .Values.app.name }} # cfserver : service name
